merge start menu into preprod
SteakBarbare/LD49 pull request #3
Opened 2021-10-02 22:33 UTC by David2he

2021-10-02 22:40 UTC, SteakBarbare requested changes

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objTutorialScreen/Create_0.gml
> +show_debug_message(xstart);
À virer

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objWKeboard/Step_0.gml
> +event_inherited();
Normal s'il y a une variable initialisée avant l'héritage ?

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objAKeboard/Step_0.gml
> +triggeredKeyboard = objKeybind.keyLeft;
Même chose, normal qu'il y ait définition de variable avant l'héritage

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objDKeboard/Step_0.gml
> +triggeredKeyboard = objKeybind.keyRight;
Same

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objEKeboard/Step_0.gml
> +triggeredKeyboard = objKeybind.eKey;
Same

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objQuickTuto/Create_0.gml
> +x = window_get_width()/2 * 1.7;
À mettre dans une variable pour les pos

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objQuickTuto/Step_0.gml
> +	image_angle = lerp(image_angle, -10, 0.01)
Égaliser le lerp pour l'effet de rotation

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objSKeboard/Step_0.gml
> +triggeredKeyboard = objKeybind.keyDown;
Ara. Nul

2021-10-02 22:40 UTC, SteakBarbare commented on PortalManager/objects/objSpaceKeboard/Step_0.gml
> +triggeredKeyboard = objKeybind.keySpaceBar;
À chier

2021-10-03 12:48 UTC, David2he reviewed
y

2021-10-03 13:07 UTC, merged